function MM_preloadImages(){var d=document;if(d.images){if(!d.MM_p){d.MM_p=new Array()}var i,j=d.MM_p.length,a=MM_preloadImages.arguments;for(i=0;i<a.length;i++){if(a[i].indexOf("#")!=0){d.MM_p[j]=new Image;d.MM_p[j++].src=a[i]}}}}function MM_swapImgRestore(){var i,x,a=document.MM_sr;for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++){x.src=x.oSrc}}function MM_findObj(n,d){var p,i,x;if(!d){d=document}if((p=n.indexOf("?"))>0&&parent.frames.length){d=parent.frames[n.substring(p+1)].document;n=n.substring(0,p)}if(!(x=d[n])&&d.all){x=d.all[n]}for(i=0;!x&&i<d.forms.length;i++){x=d.forms[i][n]}for(i=0;!x&&d.layers&&i<d.layers.length;i++){x=MM_findObj(n,d.layers[i].document)}if(!x&&d.getElementById){x=d.getElementById(n)}return x}function MM_swapImage(){var i,j=0,x,a=MM_swapImage.arguments;document.MM_sr=new Array;for(i=0;i<(a.length-2);i+=3){if((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x;if(!x.oSrc){x.oSrc=x.src}x.src=a[i+2]}}}function showLayer(a){var b=MM_findObj(a);b.style.visibility="visible";b.style.display=""}function hideLayer(a){var b=MM_findObj(a);b.style.visibility="hidden";b.style.display="none"}function showLayerImage(a,b){var c=MM_findObj(a);c.style.visibility="visible";c.style.display="";c.style.background="url("+b+")"}function open_img(a,b,c){window.open("popup.asp?showcase="+escape(a)+"&filelocation="+escape(b)+"&Desc="+escape(c),"","scrollbars=yes,resizable=yes,width=640,height=450")}function open_content_img(a){window.open("popup.asp?showcase="+escape(a)+"&filelocation="+escape("")+"&Desc=","","scrollbars=yes,resizable=yes,width=640,height=450")}function doSearchVal(a){if(a.searchbox.value.length<3){alert("Please enter at least three characters.");a.searchbox.focus();return false}return true}function load_file_doc(){}function realy_load_file_doc(a){window.open("Uploads/"+String(a),"_blank")}function MM_displayStatusMsg(a){status=a;document.MM_returnValue=true}function DynLyr(){var i,p,v,a,b=DynLyr.arguments;for(i=0;i<(b.length-2);i+=3){if((a=MM_findObj(b[i]))!=null){v=b[i+2];if(a.style){a=a.style;if(v=="show"){a.display="";a.visibility="visible"}else{a.display="none";a.visibility="hidden"}}}}}function ChkLyr(a,b,c){var d=MM_findObj(a);var e=MM_findObj(b);if(d!=null){if(d.style.visibility=="visible"){d.style.display="none";d.style.visibility="hidden"}else{d.style.display="";d.style.visibility="visible"}}}
function goCreateAnchor(a){
	var b=$("#tempa");
	var c=a.src.replace("_CMSthumbClick","");
	b.attr("href",c);	
	b.attr("rel","contentimage");	
	b.attr("title",a.alt);
	b.fancybox({'titlePosition'	: 'inside'});
	b.trigger('click');
	return false
}